### ISSUE TITLE
Migration to Firefox WebExtensions addon-style needed

### ISSUE THREAD

**Issue by mhartung** [wildskyf/TextareaCache#42]
Hi,
since I love Firefox as well as your extension, I am eager to know if you plan to migrate this addon to the WebExtensions style for keeping it working in FF 57.
Do you have such plans or will the Textarea-Cache be abandoned?

https://developer.mozilla.org/en-US/Add-ons/WebExtensions
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_legacy_Firefox_add-on

**Comment by wildskyf** [comment]
Hi, @mhartung,
this add-on is Web Extension, so it is compatible with firefox57.

Make sure you are using the right add-on: https://addons.mozilla.org/en-US/firefox/addon/textarea-cache/
There is an old version Textarea Cache, but I create another add-on page (because of some reasons...)
Remove the legacy one and install this version, and you could use Textarea Cache in your Firefox 57. :)

**Comment by mhartung** [comment]
Thank you. Indeed, I still had the old one in version 0.9.3.4 installed which has the exact same name. I will close the issue, keep up your good work.
